specific/urls.py
from specific.views import *
from django.urls import path

app_name='nothing'

urlpatterns=[
    path('sansa/',sansa,name='sansa'),
    path('arya/',arya,name='arya')

]

specificandgeneric/urls.py
from django.contrib import admin
from django.urls import path,include
from generic.views import *
import specific

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jonsnow/',jonsnow,name='jonsnow'),
    path('robb/',robb,name='robb'),

    path('specific/',include('specific.urls'))
]

generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

generic/views.py
from django.shortcuts import render

# Create your views here.

def jonsnow(request):
    return render(request,'jonsnow.html')

def  robb(request):
    return render(request,'robb.html')

specific/views.py
from django.shortcuts import render

# Create your views here.

def sansa (request):
    return render(request,'sansa.html')

def arya(request):
    return render(request,'arya.html')

templates/arya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> Arya stark is little sister to jon snow..</h1>

    <h1> She is the hero of the Winterfell</h1>
</body>
</html>

templates/jonsnow.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> Jon snow.....lord commander of the night's watch</h1>

        <h1>below show's about the jon snows relatives</h1>

        <a href="{% url 'robb' %}">Robb stark</a>
        <a href="{% url 'nothing:sansa' %}">Sansa stark</a>
        <a href="{% url 'nothing:arya' %}">Arya stark</a>
    </center>
</body>
</html>

templates/robb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> Robb stark is brother to jon snow...</h1>

        <h1>And all are called him The young Wolf...</h1>

           <h1> Died in red wedding</h1>
    </center>
</body>
</html>

templates/sansa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> Sansa stark is sister to jon snow..</h1>

    <h1> She is Lady of Winterfell...</h1>
</body>
</html>